#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class TextBlock;
                ref class Button;
                ref class CheckBox;
            }
        }
    }
}

namespace cryptutils_windows_app
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
        class MainPage_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::TextBox^ input;
        private: ::Windows::UI::Xaml::Controls::TextBox^ output;
        private: ::Windows::UI::Xaml::Controls::TextBox^ password;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock_Copy;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock_Copy1;
        private: ::Windows::UI::Xaml::Controls::Button^ execute;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ system_tips;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ mode_select;
    };
}

